"""attest.py — signs EIP-712 use-attestations that TapMarket.settle() accepts.
Generated by tapmarket-connect create-agent — no edits needed.

Mirrors the contract's digest exactly:
  DOMAIN_SEPARATOR = keccak256(abi.encode(
     keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),
     keccak256("TapMarket"), keccak256("1"), chainId, market))
  structHash = keccak256(abi.encode(ATTEST_TYPEHASH, buyer, listingId, cumulativeUses, expiry))
  digest = keccak256(0x1901 ++ DOMAIN_SEPARATOR ++ structHash)
"""
import os
import time
from dotenv import load_dotenv
from web3 import Web3
from eth_account import Account
from eth_account.messages import encode_typed_data

load_dotenv()

MARKET = Web3.to_checksum_address("0xBfd085f192d2246F1BFBe386DF399335dc894f2c")
CHAIN_ID = 84532


def sign_attestation(buyer: str, listing_id: int, cumulative_uses: int, expiry: int) -> bytes:
    """Signs a use-attestation. Returns the 65-byte signature."""
    agent_key = os.getenv("AGENT_PRIVATE_KEY")
    if not agent_key:
        raise RuntimeError("AGENT_PRIVATE_KEY not set")

    typed = {
        "types": {
            "EIP712Domain": [
                {"name": "name", "type": "string"},
                {"name": "version", "type": "string"},
                {"name": "chainId", "type": "uint256"},
                {"name": "verifyingContract", "type": "address"},
            ],
            "Attestation": [
                {"name": "buyer", "type": "address"},
                {"name": "listingId", "type": "uint256"},
                {"name": "cumulativeUses", "type": "uint256"},
                {"name": "expiry", "type": "uint256"},
            ],
        },
        "primaryType": "Attestation",
        "domain": {
            "name": "TapMarket",
            "version": "1",
            "chainId": CHAIN_ID,
            "verifyingContract": MARKET,
        },
        "message": {
            "buyer": Web3.to_checksum_address(buyer),
            "listingId": listing_id,
            "cumulativeUses": cumulative_uses,
            "expiry": expiry,
        },
    }

    encoded = encode_typed_data(full_message=typed)
    signed = Account.sign_message(encoded, private_key=agent_key)
    return signed.signature


